// SPDX-FileCopyrightText: 2026 OpenBasil Contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: basil/broker/v1/broker.proto

// Basil broker API, version 1.
//
// The broker brokers cryptographic *operations* (sign, verify, encrypt,
// decrypt, wrap, mint, issue) over key material that never leaves the vault.
// Every RPC names a catalog key/secret by its dotted `*_id`; the broker
// resolves it, checks policy against the caller's attested identity, and
// performs the operation in place. Public keys, ciphertext, tokens, and
// certificates come back; private key material does not (the sole exception is
// `IssueCertificate`, which by design releases a freshly-minted leaf private
// key to the caller).

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InvocationService_Invoke_FullMethodName = "/basil.broker.v1.InvocationService/Invoke"
)

// InvocationServiceClient is the client API for InvocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Disabled-by-default transport-neutral invocation service. Local clients keep
// using the typed gRPC services over Unix sockets.
type InvocationServiceClient interface {
	// Submit a sealed invocation message.
	Invoke(ctx context.Context, in *SealedRequest, opts ...grpc.CallOption) (*SealedResponse, error)
}

type invocationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInvocationServiceClient(cc grpc.ClientConnInterface) InvocationServiceClient {
	return &invocationServiceClient{cc}
}

func (c *invocationServiceClient) Invoke(ctx context.Context, in *SealedRequest, opts ...grpc.CallOption) (*SealedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SealedResponse)
	err := c.cc.Invoke(ctx, InvocationService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvocationServiceServer is the server API for InvocationService service.
// All implementations must embed UnimplementedInvocationServiceServer
// for forward compatibility.
//
// Disabled-by-default transport-neutral invocation service. Local clients keep
// using the typed gRPC services over Unix sockets.
type InvocationServiceServer interface {
	// Submit a sealed invocation message.
	Invoke(context.Context, *SealedRequest) (*SealedResponse, error)
	mustEmbedUnimplementedInvocationServiceServer()
}

// UnimplementedInvocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvocationServiceServer struct{}

func (UnimplementedInvocationServiceServer) Invoke(context.Context, *SealedRequest) (*SealedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedInvocationServiceServer) mustEmbedUnimplementedInvocationServiceServer() {}
func (UnimplementedInvocationServiceServer) testEmbeddedByValue()                           {}

// UnsafeInvocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvocationServiceServer will
// result in compilation errors.
type UnsafeInvocationServiceServer interface {
	mustEmbedUnimplementedInvocationServiceServer()
}

func RegisterInvocationServiceServer(s grpc.ServiceRegistrar, srv InvocationServiceServer) {
	// If the following call panics, it indicates UnimplementedInvocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InvocationService_ServiceDesc, srv)
}

func _InvocationService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SealedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvocationServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvocationService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvocationServiceServer).Invoke(ctx, req.(*SealedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InvocationService_ServiceDesc is the grpc.ServiceDesc for InvocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basil.broker.v1.InvocationService",
	HandlerType: (*InvocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _InvocationService_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "basil/broker/v1/broker.proto",
}

const (
	SigningService_NewKey_FullMethodName       = "/basil.broker.v1.SigningService/NewKey"
	SigningService_Import_FullMethodName       = "/basil.broker.v1.SigningService/Import"
	SigningService_ImportSet_FullMethodName    = "/basil.broker.v1.SigningService/ImportSet"
	SigningService_Sign_FullMethodName         = "/basil.broker.v1.SigningService/Sign"
	SigningService_Verify_FullMethodName       = "/basil.broker.v1.SigningService/Verify"
	SigningService_GetPublicKey_FullMethodName = "/basil.broker.v1.SigningService/GetPublicKey"
)

// SigningServiceClient is the client API for SigningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Create, import, and use asymmetric signing keys. Private key material is
// generated or imported into the vault and never returned.
type SigningServiceClient interface {
	// Generate a new key under a catalog name.
	NewKey(ctx context.Context, in *NewKeyRequest, opts ...grpc.CallOption) (*NewKeyResponse, error)
	// Import caller-supplied key material under a catalog name.
	Import(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*NewKeyResponse, error)
	// Import several keys in one authorized call.
	ImportSet(ctx context.Context, in *ImportSetRequest, opts ...grpc.CallOption) (*ImportSetResponse, error)
	// Sign a message with a catalog key (the key signs in place).
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	// Verify a signature with a catalog key.
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	// Fetch a key's public half by catalog name and optional version.
	GetPublicKey(ctx context.Context, in *GetPublicKeyRequest, opts ...grpc.CallOption) (*GetPublicKeyResponse, error)
}

type signingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSigningServiceClient(cc grpc.ClientConnInterface) SigningServiceClient {
	return &signingServiceClient{cc}
}

func (c *signingServiceClient) NewKey(ctx context.Context, in *NewKeyRequest, opts ...grpc.CallOption) (*NewKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewKeyResponse)
	err := c.cc.Invoke(ctx, SigningService_NewKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) Import(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*NewKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewKeyResponse)
	err := c.cc.Invoke(ctx, SigningService_Import_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) ImportSet(ctx context.Context, in *ImportSetRequest, opts ...grpc.CallOption) (*ImportSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportSetResponse)
	err := c.cc.Invoke(ctx, SigningService_ImportSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, SigningService_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, SigningService_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) GetPublicKey(ctx context.Context, in *GetPublicKeyRequest, opts ...grpc.CallOption) (*GetPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicKeyResponse)
	err := c.cc.Invoke(ctx, SigningService_GetPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SigningServiceServer is the server API for SigningService service.
// All implementations must embed UnimplementedSigningServiceServer
// for forward compatibility.
//
// Create, import, and use asymmetric signing keys. Private key material is
// generated or imported into the vault and never returned.
type SigningServiceServer interface {
	// Generate a new key under a catalog name.
	NewKey(context.Context, *NewKeyRequest) (*NewKeyResponse, error)
	// Import caller-supplied key material under a catalog name.
	Import(context.Context, *ImportRequest) (*NewKeyResponse, error)
	// Import several keys in one authorized call.
	ImportSet(context.Context, *ImportSetRequest) (*ImportSetResponse, error)
	// Sign a message with a catalog key (the key signs in place).
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	// Verify a signature with a catalog key.
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	// Fetch a key's public half by catalog name and optional version.
	GetPublicKey(context.Context, *GetPublicKeyRequest) (*GetPublicKeyResponse, error)
	mustEmbedUnimplementedSigningServiceServer()
}

// UnimplementedSigningServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSigningServiceServer struct{}

func (UnimplementedSigningServiceServer) NewKey(context.Context, *NewKeyRequest) (*NewKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NewKey not implemented")
}
func (UnimplementedSigningServiceServer) Import(context.Context, *ImportRequest) (*NewKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Import not implemented")
}
func (UnimplementedSigningServiceServer) ImportSet(context.Context, *ImportSetRequest) (*ImportSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportSet not implemented")
}
func (UnimplementedSigningServiceServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedSigningServiceServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedSigningServiceServer) GetPublicKey(context.Context, *GetPublicKeyRequest) (*GetPublicKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicKey not implemented")
}
func (UnimplementedSigningServiceServer) mustEmbedUnimplementedSigningServiceServer() {}
func (UnimplementedSigningServiceServer) testEmbeddedByValue()                        {}

// UnsafeSigningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SigningServiceServer will
// result in compilation errors.
type UnsafeSigningServiceServer interface {
	mustEmbedUnimplementedSigningServiceServer()
}

func RegisterSigningServiceServer(s grpc.ServiceRegistrar, srv SigningServiceServer) {
	// If the following call panics, it indicates UnimplementedSigningServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SigningService_ServiceDesc, srv)
}

func _SigningService_NewKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).NewKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_NewKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).NewKey(ctx, req.(*NewKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_Import_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).Import(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_Import_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).Import(ctx, req.(*ImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_ImportSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).ImportSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_ImportSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).ImportSet(ctx, req.(*ImportSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SigningService_GetPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).GetPublicKey(ctx, req.(*GetPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SigningService_ServiceDesc is the grpc.ServiceDesc for SigningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SigningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basil.broker.v1.SigningService",
	HandlerType: (*SigningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewKey",
			Handler:    _SigningService_NewKey_Handler,
		},
		{
			MethodName: "Import",
			Handler:    _SigningService_Import_Handler,
		},
		{
			MethodName: "ImportSet",
			Handler:    _SigningService_ImportSet_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _SigningService_Sign_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _SigningService_Verify_Handler,
		},
		{
			MethodName: "GetPublicKey",
			Handler:    _SigningService_GetPublicKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "basil/broker/v1/broker.proto",
}

const (
	AeadService_Encrypt_FullMethodName        = "/basil.broker.v1.AeadService/Encrypt"
	AeadService_Decrypt_FullMethodName        = "/basil.broker.v1.AeadService/Decrypt"
	AeadService_WrapEnvelope_FullMethodName   = "/basil.broker.v1.AeadService/WrapEnvelope"
	AeadService_UnwrapEnvelope_FullMethodName = "/basil.broker.v1.AeadService/UnwrapEnvelope"
	AeadService_UnsealCose_FullMethodName     = "/basil.broker.v1.AeadService/UnsealCose"
)

// AeadServiceClient is the client API for AeadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Authenticated encryption with broker-owned nonces, plus KEM enveloping.
type AeadServiceClient interface {
	// Encrypt plaintext; the broker generates the nonce.
	Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error)
	// Decrypt a Basil ciphertext envelope.
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
	// Wrap plaintext under a KEM recipient key.
	WrapEnvelope(ctx context.Context, in *WrapEnvelopeRequest, opts ...grpc.CallOption) (*WrapEnvelopeResponse, error)
	// Unwrap a KEM envelope.
	UnwrapEnvelope(ctx context.Context, in *UnwrapEnvelopeRequest, opts ...grpc.CallOption) (*UnwrapEnvelopeResponse, error)
	// Open a COSE_Encrypt sealed to a backend-custodied X25519 recipient key.
	UnsealCose(ctx context.Context, in *UnsealCoseRequest, opts ...grpc.CallOption) (*UnsealCoseResponse, error)
}

type aeadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAeadServiceClient(cc grpc.ClientConnInterface) AeadServiceClient {
	return &aeadServiceClient{cc}
}

func (c *aeadServiceClient) Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptResponse)
	err := c.cc.Invoke(ctx, AeadService_Encrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeadServiceClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptResponse)
	err := c.cc.Invoke(ctx, AeadService_Decrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeadServiceClient) WrapEnvelope(ctx context.Context, in *WrapEnvelopeRequest, opts ...grpc.CallOption) (*WrapEnvelopeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WrapEnvelopeResponse)
	err := c.cc.Invoke(ctx, AeadService_WrapEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeadServiceClient) UnwrapEnvelope(ctx context.Context, in *UnwrapEnvelopeRequest, opts ...grpc.CallOption) (*UnwrapEnvelopeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnwrapEnvelopeResponse)
	err := c.cc.Invoke(ctx, AeadService_UnwrapEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aeadServiceClient) UnsealCose(ctx context.Context, in *UnsealCoseRequest, opts ...grpc.CallOption) (*UnsealCoseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsealCoseResponse)
	err := c.cc.Invoke(ctx, AeadService_UnsealCose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AeadServiceServer is the server API for AeadService service.
// All implementations must embed UnimplementedAeadServiceServer
// for forward compatibility.
//
// Authenticated encryption with broker-owned nonces, plus KEM enveloping.
type AeadServiceServer interface {
	// Encrypt plaintext; the broker generates the nonce.
	Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error)
	// Decrypt a Basil ciphertext envelope.
	Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error)
	// Wrap plaintext under a KEM recipient key.
	WrapEnvelope(context.Context, *WrapEnvelopeRequest) (*WrapEnvelopeResponse, error)
	// Unwrap a KEM envelope.
	UnwrapEnvelope(context.Context, *UnwrapEnvelopeRequest) (*UnwrapEnvelopeResponse, error)
	// Open a COSE_Encrypt sealed to a backend-custodied X25519 recipient key.
	UnsealCose(context.Context, *UnsealCoseRequest) (*UnsealCoseResponse, error)
	mustEmbedUnimplementedAeadServiceServer()
}

// UnimplementedAeadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAeadServiceServer struct{}

func (UnimplementedAeadServiceServer) Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Encrypt not implemented")
}
func (UnimplementedAeadServiceServer) Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decrypt not implemented")
}
func (UnimplementedAeadServiceServer) WrapEnvelope(context.Context, *WrapEnvelopeRequest) (*WrapEnvelopeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WrapEnvelope not implemented")
}
func (UnimplementedAeadServiceServer) UnwrapEnvelope(context.Context, *UnwrapEnvelopeRequest) (*UnwrapEnvelopeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnwrapEnvelope not implemented")
}
func (UnimplementedAeadServiceServer) UnsealCose(context.Context, *UnsealCoseRequest) (*UnsealCoseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsealCose not implemented")
}
func (UnimplementedAeadServiceServer) mustEmbedUnimplementedAeadServiceServer() {}
func (UnimplementedAeadServiceServer) testEmbeddedByValue()                     {}

// UnsafeAeadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AeadServiceServer will
// result in compilation errors.
type UnsafeAeadServiceServer interface {
	mustEmbedUnimplementedAeadServiceServer()
}

func RegisterAeadServiceServer(s grpc.ServiceRegistrar, srv AeadServiceServer) {
	// If the following call panics, it indicates UnimplementedAeadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AeadService_ServiceDesc, srv)
}

func _AeadService_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeadServiceServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeadService_Encrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeadServiceServer).Encrypt(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeadService_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeadServiceServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeadService_Decrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeadServiceServer).Decrypt(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeadService_WrapEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WrapEnvelopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeadServiceServer).WrapEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeadService_WrapEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeadServiceServer).WrapEnvelope(ctx, req.(*WrapEnvelopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeadService_UnwrapEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnwrapEnvelopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeadServiceServer).UnwrapEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeadService_UnwrapEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeadServiceServer).UnwrapEnvelope(ctx, req.(*UnwrapEnvelopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AeadService_UnsealCose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsealCoseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AeadServiceServer).UnsealCose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AeadService_UnsealCose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AeadServiceServer).UnsealCose(ctx, req.(*UnsealCoseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AeadService_ServiceDesc is the grpc.ServiceDesc for AeadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AeadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basil.broker.v1.AeadService",
	HandlerType: (*AeadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encrypt",
			Handler:    _AeadService_Encrypt_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _AeadService_Decrypt_Handler,
		},
		{
			MethodName: "WrapEnvelope",
			Handler:    _AeadService_WrapEnvelope_Handler,
		},
		{
			MethodName: "UnwrapEnvelope",
			Handler:    _AeadService_UnwrapEnvelope_Handler,
		},
		{
			MethodName: "UnsealCose",
			Handler:    _AeadService_UnsealCose_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "basil/broker/v1/broker.proto",
}

const (
	SecretService_GetSecret_FullMethodName    = "/basil.broker.v1.SecretService/GetSecret"
	SecretService_SetSecret_FullMethodName    = "/basil.broker.v1.SecretService/SetSecret"
	SecretService_RotateSecret_FullMethodName = "/basil.broker.v1.SecretService/RotateSecret"
	SecretService_ListCatalog_FullMethodName  = "/basil.broker.v1.SecretService/ListCatalog"
)

// SecretServiceClient is the client API for SecretService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Store, fetch, rotate, and list opaque secrets and catalog entries.
type SecretServiceClient interface {
	// Fetch a secret payload by id and optional version.
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error)
	// Store a secret payload, creating a new version.
	SetSecret(ctx context.Context, in *SetSecretRequest, opts ...grpc.CallOption) (*SetSecretResponse, error)
	// Rotate a secret to a new version.
	RotateSecret(ctx context.Context, in *RotateSecretRequest, opts ...grpc.CallOption) (*RotateSecretResponse, error)
	// Stream the catalog entries visible to the caller.
	ListCatalog(ctx context.Context, in *ListCatalogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CatalogEntry], error)
}

type secretServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretServiceClient(cc grpc.ClientConnInterface) SecretServiceClient {
	return &secretServiceClient{cc}
}

func (c *secretServiceClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretResponse)
	err := c.cc.Invoke(ctx, SecretService_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) SetSecret(ctx context.Context, in *SetSecretRequest, opts ...grpc.CallOption) (*SetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSecretResponse)
	err := c.cc.Invoke(ctx, SecretService_SetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) RotateSecret(ctx context.Context, in *RotateSecretRequest, opts ...grpc.CallOption) (*RotateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateSecretResponse)
	err := c.cc.Invoke(ctx, SecretService_RotateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretServiceClient) ListCatalog(ctx context.Context, in *ListCatalogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CatalogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SecretService_ServiceDesc.Streams[0], SecretService_ListCatalog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListCatalogRequest, CatalogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecretService_ListCatalogClient = grpc.ServerStreamingClient[CatalogEntry]

// SecretServiceServer is the server API for SecretService service.
// All implementations must embed UnimplementedSecretServiceServer
// for forward compatibility.
//
// Store, fetch, rotate, and list opaque secrets and catalog entries.
type SecretServiceServer interface {
	// Fetch a secret payload by id and optional version.
	GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error)
	// Store a secret payload, creating a new version.
	SetSecret(context.Context, *SetSecretRequest) (*SetSecretResponse, error)
	// Rotate a secret to a new version.
	RotateSecret(context.Context, *RotateSecretRequest) (*RotateSecretResponse, error)
	// Stream the catalog entries visible to the caller.
	ListCatalog(*ListCatalogRequest, grpc.ServerStreamingServer[CatalogEntry]) error
	mustEmbedUnimplementedSecretServiceServer()
}

// UnimplementedSecretServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretServiceServer struct{}

func (UnimplementedSecretServiceServer) GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedSecretServiceServer) SetSecret(context.Context, *SetSecretRequest) (*SetSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSecret not implemented")
}
func (UnimplementedSecretServiceServer) RotateSecret(context.Context, *RotateSecretRequest) (*RotateSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateSecret not implemented")
}
func (UnimplementedSecretServiceServer) ListCatalog(*ListCatalogRequest, grpc.ServerStreamingServer[CatalogEntry]) error {
	return status.Error(codes.Unimplemented, "method ListCatalog not implemented")
}
func (UnimplementedSecretServiceServer) mustEmbedUnimplementedSecretServiceServer() {}
func (UnimplementedSecretServiceServer) testEmbeddedByValue()                       {}

// UnsafeSecretServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretServiceServer will
// result in compilation errors.
type UnsafeSecretServiceServer interface {
	mustEmbedUnimplementedSecretServiceServer()
}

func RegisterSecretServiceServer(s grpc.ServiceRegistrar, srv SecretServiceServer) {
	// If the following call panics, it indicates UnimplementedSecretServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretService_ServiceDesc, srv)
}

func _SecretService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_SetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).SetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_SetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).SetSecret(ctx, req.(*SetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_RotateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretServiceServer).RotateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretService_RotateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretServiceServer).RotateSecret(ctx, req.(*RotateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretService_ListCatalog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListCatalogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SecretServiceServer).ListCatalog(m, &grpc.GenericServerStream[ListCatalogRequest, CatalogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SecretService_ListCatalogServer = grpc.ServerStreamingServer[CatalogEntry]

// SecretService_ServiceDesc is the grpc.ServiceDesc for SecretService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basil.broker.v1.SecretService",
	HandlerType: (*SecretServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecret",
			Handler:    _SecretService_GetSecret_Handler,
		},
		{
			MethodName: "SetSecret",
			Handler:    _SecretService_SetSecret_Handler,
		},
		{
			MethodName: "RotateSecret",
			Handler:    _SecretService_RotateSecret_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListCatalog",
			Handler:       _SecretService_ListCatalog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "basil/broker/v1/broker.proto",
}

const (
	MintingService_MintJwt_FullMethodName          = "/basil.broker.v1.MintingService/MintJwt"
	MintingService_IssueCertificate_FullMethodName = "/basil.broker.v1.MintingService/IssueCertificate"
)

// MintingServiceClient is the client API for MintingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Mint short-lived generic JWT credentials and issue X.509 leaves, each signed
// in place by a catalog key.
type MintingServiceClient interface {
	// Mint a generic JWT with caller-supplied claims.
	MintJwt(ctx context.Context, in *MintJwtRequest, opts ...grpc.CallOption) (*CredentialResponse, error)
	// Issue a DNS/IP-SAN X.509 leaf certificate from a backend PKI role.
	IssueCertificate(ctx context.Context, in *IssueCertificateRequest, opts ...grpc.CallOption) (*IssueCertificateResponse, error)
}

type mintingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMintingServiceClient(cc grpc.ClientConnInterface) MintingServiceClient {
	return &mintingServiceClient{cc}
}

func (c *mintingServiceClient) MintJwt(ctx context.Context, in *MintJwtRequest, opts ...grpc.CallOption) (*CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialResponse)
	err := c.cc.Invoke(ctx, MintingService_MintJwt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mintingServiceClient) IssueCertificate(ctx context.Context, in *IssueCertificateRequest, opts ...grpc.CallOption) (*IssueCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueCertificateResponse)
	err := c.cc.Invoke(ctx, MintingService_IssueCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MintingServiceServer is the server API for MintingService service.
// All implementations must embed UnimplementedMintingServiceServer
// for forward compatibility.
//
// Mint short-lived generic JWT credentials and issue X.509 leaves, each signed
// in place by a catalog key.
type MintingServiceServer interface {
	// Mint a generic JWT with caller-supplied claims.
	MintJwt(context.Context, *MintJwtRequest) (*CredentialResponse, error)
	// Issue a DNS/IP-SAN X.509 leaf certificate from a backend PKI role.
	IssueCertificate(context.Context, *IssueCertificateRequest) (*IssueCertificateResponse, error)
	mustEmbedUnimplementedMintingServiceServer()
}

// UnimplementedMintingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMintingServiceServer struct{}

func (UnimplementedMintingServiceServer) MintJwt(context.Context, *MintJwtRequest) (*CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintJwt not implemented")
}
func (UnimplementedMintingServiceServer) IssueCertificate(context.Context, *IssueCertificateRequest) (*IssueCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueCertificate not implemented")
}
func (UnimplementedMintingServiceServer) mustEmbedUnimplementedMintingServiceServer() {}
func (UnimplementedMintingServiceServer) testEmbeddedByValue()                        {}

// UnsafeMintingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MintingServiceServer will
// result in compilation errors.
type UnsafeMintingServiceServer interface {
	mustEmbedUnimplementedMintingServiceServer()
}

func RegisterMintingServiceServer(s grpc.ServiceRegistrar, srv MintingServiceServer) {
	// If the following call panics, it indicates UnimplementedMintingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MintingService_ServiceDesc, srv)
}

func _MintingService_MintJwt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintJwtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MintingServiceServer).MintJwt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MintingService_MintJwt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MintingServiceServer).MintJwt(ctx, req.(*MintJwtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MintingService_IssueCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MintingServiceServer).IssueCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MintingService_IssueCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MintingServiceServer).IssueCertificate(ctx, req.(*IssueCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MintingService_ServiceDesc is the grpc.ServiceDesc for MintingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MintingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basil.broker.v1.MintingService",
	HandlerType: (*MintingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintJwt",
			Handler:    _MintingService_MintJwt_Handler,
		},
		{
			MethodName: "IssueCertificate",
			Handler:    _MintingService_IssueCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "basil/broker/v1/broker.proto",
}

const (
	NatsService_MintNatsUser_FullMethodName     = "/basil.broker.v1.NatsService/MintNatsUser"
	NatsService_MintNatsAccount_FullMethodName  = "/basil.broker.v1.NatsService/MintNatsAccount"
	NatsService_MintNatsOperator_FullMethodName = "/basil.broker.v1.NatsService/MintNatsOperator"
	NatsService_MintNatsSigner_FullMethodName   = "/basil.broker.v1.NatsService/MintNatsSigner"
	NatsService_MintNatsServer_FullMethodName   = "/basil.broker.v1.NatsService/MintNatsServer"
	NatsService_MintNatsCurve_FullMethodName    = "/basil.broker.v1.NatsService/MintNatsCurve"
	NatsService_EncryptNatsCurve_FullMethodName = "/basil.broker.v1.NatsService/EncryptNatsCurve"
	NatsService_DecryptNatsCurve_FullMethodName = "/basil.broker.v1.NatsService/DecryptNatsCurve"
	NatsService_SignNatsJwt_FullMethodName      = "/basil.broker.v1.NatsService/SignNatsJwt"
	NatsService_ValidateNatsJwt_FullMethodName  = "/basil.broker.v1.NatsService/ValidateNatsJwt"
)

// NatsServiceClient is the client API for NatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NATS identity and JWT operations.
type NatsServiceClient interface {
	// Mint a NATS user JWT signed by an account key.
	MintNatsUser(ctx context.Context, in *MintNatsUserRequest, opts ...grpc.CallOption) (*CredentialResponse, error)
	// Mint a NATS account JWT signed by an operator key (or self-signed).
	MintNatsAccount(ctx context.Context, in *MintNatsAccountRequest, opts ...grpc.CallOption) (*CredentialResponse, error)
	// Mint a NATS operator JWT (usually self-signed).
	MintNatsOperator(ctx context.Context, in *MintNatsOperatorRequest, opts ...grpc.CallOption) (*CredentialResponse, error)
	// Mint a NATS account/operator signing-key JWT.
	MintNatsSigner(ctx context.Context, in *MintNatsSignerRequest, opts ...grpc.CallOption) (*CredentialResponse, error)
	// Mint a NATS server JWT.
	MintNatsServer(ctx context.Context, in *MintNatsServerRequest, opts ...grpc.CallOption) (*CredentialResponse, error)
	// Mint a NATS curve (x25519 xkey) JWT.
	MintNatsCurve(ctx context.Context, in *MintNatsCurveRequest, opts ...grpc.CallOption) (*CredentialResponse, error)
	// Encrypt a payload with a custodied NATS curve xkey to a peer xkey.
	EncryptNatsCurve(ctx context.Context, in *EncryptNatsCurveRequest, opts ...grpc.CallOption) (*EncryptNatsCurveResponse, error)
	// Decrypt a NATS curve xkey box from a peer xkey.
	DecryptNatsCurve(ctx context.Context, in *DecryptNatsCurveRequest, opts ...grpc.CallOption) (*DecryptNatsCurveResponse, error)
	// Validate and sign a caller-supplied NATS JWT claim document.
	SignNatsJwt(ctx context.Context, in *SignNatsJwtRequest, opts ...grpc.CallOption) (*CredentialResponse, error)
	// Validate a caller-supplied NATS JWT against candidate signers.
	ValidateNatsJwt(ctx context.Context, in *ValidateNatsJwtRequest, opts ...grpc.CallOption) (*ValidateNatsJwtResponse, error)
}

type natsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNatsServiceClient(cc grpc.ClientConnInterface) NatsServiceClient {
	return &natsServiceClient{cc}
}

func (c *natsServiceClient) MintNatsUser(ctx context.Context, in *MintNatsUserRequest, opts ...grpc.CallOption) (*CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialResponse)
	err := c.cc.Invoke(ctx, NatsService_MintNatsUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *natsServiceClient) MintNatsAccount(ctx context.Context, in *MintNatsAccountRequest, opts ...grpc.CallOption) (*CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialResponse)
	err := c.cc.Invoke(ctx, NatsService_MintNatsAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *natsServiceClient) MintNatsOperator(ctx context.Context, in *MintNatsOperatorRequest, opts ...grpc.CallOption) (*CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialResponse)
	err := c.cc.Invoke(ctx, NatsService_MintNatsOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *natsServiceClient) MintNatsSigner(ctx context.Context, in *MintNatsSignerRequest, opts ...grpc.CallOption) (*CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialResponse)
	err := c.cc.Invoke(ctx, NatsService_MintNatsSigner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *natsServiceClient) MintNatsServer(ctx context.Context, in *MintNatsServerRequest, opts ...grpc.CallOption) (*CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialResponse)
	err := c.cc.Invoke(ctx, NatsService_MintNatsServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *natsServiceClient) MintNatsCurve(ctx context.Context, in *MintNatsCurveRequest, opts ...grpc.CallOption) (*CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialResponse)
	err := c.cc.Invoke(ctx, NatsService_MintNatsCurve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *natsServiceClient) EncryptNatsCurve(ctx context.Context, in *EncryptNatsCurveRequest, opts ...grpc.CallOption) (*EncryptNatsCurveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptNatsCurveResponse)
	err := c.cc.Invoke(ctx, NatsService_EncryptNatsCurve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *natsServiceClient) DecryptNatsCurve(ctx context.Context, in *DecryptNatsCurveRequest, opts ...grpc.CallOption) (*DecryptNatsCurveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptNatsCurveResponse)
	err := c.cc.Invoke(ctx, NatsService_DecryptNatsCurve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *natsServiceClient) SignNatsJwt(ctx context.Context, in *SignNatsJwtRequest, opts ...grpc.CallOption) (*CredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialResponse)
	err := c.cc.Invoke(ctx, NatsService_SignNatsJwt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *natsServiceClient) ValidateNatsJwt(ctx context.Context, in *ValidateNatsJwtRequest, opts ...grpc.CallOption) (*ValidateNatsJwtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateNatsJwtResponse)
	err := c.cc.Invoke(ctx, NatsService_ValidateNatsJwt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NatsServiceServer is the server API for NatsService service.
// All implementations must embed UnimplementedNatsServiceServer
// for forward compatibility.
//
// NATS identity and JWT operations.
type NatsServiceServer interface {
	// Mint a NATS user JWT signed by an account key.
	MintNatsUser(context.Context, *MintNatsUserRequest) (*CredentialResponse, error)
	// Mint a NATS account JWT signed by an operator key (or self-signed).
	MintNatsAccount(context.Context, *MintNatsAccountRequest) (*CredentialResponse, error)
	// Mint a NATS operator JWT (usually self-signed).
	MintNatsOperator(context.Context, *MintNatsOperatorRequest) (*CredentialResponse, error)
	// Mint a NATS account/operator signing-key JWT.
	MintNatsSigner(context.Context, *MintNatsSignerRequest) (*CredentialResponse, error)
	// Mint a NATS server JWT.
	MintNatsServer(context.Context, *MintNatsServerRequest) (*CredentialResponse, error)
	// Mint a NATS curve (x25519 xkey) JWT.
	MintNatsCurve(context.Context, *MintNatsCurveRequest) (*CredentialResponse, error)
	// Encrypt a payload with a custodied NATS curve xkey to a peer xkey.
	EncryptNatsCurve(context.Context, *EncryptNatsCurveRequest) (*EncryptNatsCurveResponse, error)
	// Decrypt a NATS curve xkey box from a peer xkey.
	DecryptNatsCurve(context.Context, *DecryptNatsCurveRequest) (*DecryptNatsCurveResponse, error)
	// Validate and sign a caller-supplied NATS JWT claim document.
	SignNatsJwt(context.Context, *SignNatsJwtRequest) (*CredentialResponse, error)
	// Validate a caller-supplied NATS JWT against candidate signers.
	ValidateNatsJwt(context.Context, *ValidateNatsJwtRequest) (*ValidateNatsJwtResponse, error)
	mustEmbedUnimplementedNatsServiceServer()
}

// UnimplementedNatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNatsServiceServer struct{}

func (UnimplementedNatsServiceServer) MintNatsUser(context.Context, *MintNatsUserRequest) (*CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintNatsUser not implemented")
}
func (UnimplementedNatsServiceServer) MintNatsAccount(context.Context, *MintNatsAccountRequest) (*CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintNatsAccount not implemented")
}
func (UnimplementedNatsServiceServer) MintNatsOperator(context.Context, *MintNatsOperatorRequest) (*CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintNatsOperator not implemented")
}
func (UnimplementedNatsServiceServer) MintNatsSigner(context.Context, *MintNatsSignerRequest) (*CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintNatsSigner not implemented")
}
func (UnimplementedNatsServiceServer) MintNatsServer(context.Context, *MintNatsServerRequest) (*CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintNatsServer not implemented")
}
func (UnimplementedNatsServiceServer) MintNatsCurve(context.Context, *MintNatsCurveRequest) (*CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintNatsCurve not implemented")
}
func (UnimplementedNatsServiceServer) EncryptNatsCurve(context.Context, *EncryptNatsCurveRequest) (*EncryptNatsCurveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EncryptNatsCurve not implemented")
}
func (UnimplementedNatsServiceServer) DecryptNatsCurve(context.Context, *DecryptNatsCurveRequest) (*DecryptNatsCurveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecryptNatsCurve not implemented")
}
func (UnimplementedNatsServiceServer) SignNatsJwt(context.Context, *SignNatsJwtRequest) (*CredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignNatsJwt not implemented")
}
func (UnimplementedNatsServiceServer) ValidateNatsJwt(context.Context, *ValidateNatsJwtRequest) (*ValidateNatsJwtResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateNatsJwt not implemented")
}
func (UnimplementedNatsServiceServer) mustEmbedUnimplementedNatsServiceServer() {}
func (UnimplementedNatsServiceServer) testEmbeddedByValue()                     {}

// UnsafeNatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NatsServiceServer will
// result in compilation errors.
type UnsafeNatsServiceServer interface {
	mustEmbedUnimplementedNatsServiceServer()
}

func RegisterNatsServiceServer(s grpc.ServiceRegistrar, srv NatsServiceServer) {
	// If the following call panics, it indicates UnimplementedNatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NatsService_ServiceDesc, srv)
}

func _NatsService_MintNatsUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintNatsUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NatsServiceServer).MintNatsUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NatsService_MintNatsUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NatsServiceServer).MintNatsUser(ctx, req.(*MintNatsUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NatsService_MintNatsAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintNatsAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NatsServiceServer).MintNatsAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NatsService_MintNatsAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NatsServiceServer).MintNatsAccount(ctx, req.(*MintNatsAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NatsService_MintNatsOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintNatsOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NatsServiceServer).MintNatsOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NatsService_MintNatsOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NatsServiceServer).MintNatsOperator(ctx, req.(*MintNatsOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NatsService_MintNatsSigner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintNatsSignerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NatsServiceServer).MintNatsSigner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NatsService_MintNatsSigner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NatsServiceServer).MintNatsSigner(ctx, req.(*MintNatsSignerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NatsService_MintNatsServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintNatsServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NatsServiceServer).MintNatsServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NatsService_MintNatsServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NatsServiceServer).MintNatsServer(ctx, req.(*MintNatsServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NatsService_MintNatsCurve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintNatsCurveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NatsServiceServer).MintNatsCurve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NatsService_MintNatsCurve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NatsServiceServer).MintNatsCurve(ctx, req.(*MintNatsCurveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NatsService_EncryptNatsCurve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptNatsCurveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NatsServiceServer).EncryptNatsCurve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NatsService_EncryptNatsCurve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NatsServiceServer).EncryptNatsCurve(ctx, req.(*EncryptNatsCurveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NatsService_DecryptNatsCurve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptNatsCurveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NatsServiceServer).DecryptNatsCurve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NatsService_DecryptNatsCurve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NatsServiceServer).DecryptNatsCurve(ctx, req.(*DecryptNatsCurveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NatsService_SignNatsJwt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignNatsJwtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NatsServiceServer).SignNatsJwt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NatsService_SignNatsJwt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NatsServiceServer).SignNatsJwt(ctx, req.(*SignNatsJwtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NatsService_ValidateNatsJwt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateNatsJwtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NatsServiceServer).ValidateNatsJwt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NatsService_ValidateNatsJwt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NatsServiceServer).ValidateNatsJwt(ctx, req.(*ValidateNatsJwtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NatsService_ServiceDesc is the grpc.ServiceDesc for NatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basil.broker.v1.NatsService",
	HandlerType: (*NatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintNatsUser",
			Handler:    _NatsService_MintNatsUser_Handler,
		},
		{
			MethodName: "MintNatsAccount",
			Handler:    _NatsService_MintNatsAccount_Handler,
		},
		{
			MethodName: "MintNatsOperator",
			Handler:    _NatsService_MintNatsOperator_Handler,
		},
		{
			MethodName: "MintNatsSigner",
			Handler:    _NatsService_MintNatsSigner_Handler,
		},
		{
			MethodName: "MintNatsServer",
			Handler:    _NatsService_MintNatsServer_Handler,
		},
		{
			MethodName: "MintNatsCurve",
			Handler:    _NatsService_MintNatsCurve_Handler,
		},
		{
			MethodName: "EncryptNatsCurve",
			Handler:    _NatsService_EncryptNatsCurve_Handler,
		},
		{
			MethodName: "DecryptNatsCurve",
			Handler:    _NatsService_DecryptNatsCurve_Handler,
		},
		{
			MethodName: "SignNatsJwt",
			Handler:    _NatsService_SignNatsJwt_Handler,
		},
		{
			MethodName: "ValidateNatsJwt",
			Handler:    _NatsService_ValidateNatsJwt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "basil/broker/v1/broker.proto",
}

const (
	AdminService_Status_FullMethodName    = "/basil.broker.v1.AdminService/Status"
	AdminService_Health_FullMethodName    = "/basil.broker.v1.AdminService/Health"
	AdminService_Readiness_FullMethodName = "/basil.broker.v1.AdminService/Readiness"
	AdminService_Watch_FullMethodName     = "/basil.broker.v1.AdminService/Watch"
	AdminService_Reload_FullMethodName    = "/basil.broker.v1.AdminService/Reload"
	AdminService_Explain_FullMethodName   = "/basil.broker.v1.AdminService/Explain"
	AdminService_Revoke_FullMethodName    = "/basil.broker.v1.AdminService/Revoke"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Broker introspection and change notifications.
type AdminServiceClient interface {
	// Report backend, version, and protocol.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Liveness: is the broker process up and serving the socket? Cheap,
	// always-answerable, never touches a backend. A successful response means the
	// daemon is alive; it says nothing about whether it can serve data-plane ops.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Readiness: can the broker actually serve? Probes per-backend reachability
	// and every catalog key's material, and reports whether serving would fail
	// closed (an unreachable backend, or a `missing=error` key whose material is
	// absent). The detail is a non-secret SUMMARY (counts + a coarse reason): it
	// never returns key names, key material, or the catalog inventory.
	Readiness(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessResponse, error)
	// Stream change events (key rotations, bundle changes, revocations).
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Hot-reload the catalog/policy generation FROM DISK (basil-atq). The broker
	// re-reads the catalog/policy from the same on-disk paths it was started with,
	// runs the full startup/`check` validation, and, on success, atomically swaps
	// in a new generation. This RPC is permission-gated by a dedicated `reload`
	// policy op (NOT implied by any data-plane grant) and peer-cred attested; both
	// the success (generation change) and a denial are audited.
	//
	// TRUST BOUNDARY: the request carries NO catalog/policy bytes: the only input
	// is `check` (dry-run). Config is taken from disk (Nix/root-owned) only, so the
	// wire can never inject policy. A `check=true` request validates the candidate
	// and reports the would-be outcome WITHOUT swapping the serving generation.
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error)
	// Explain a policy decision against the currently serving generation. This is
	// permission-gated by a dedicated `explain` admin op over `broker.explain`
	// because it exposes policy reachability; no data-plane grant implies it.
	Explain(ctx context.Context, in *ExplainRequest, opts ...grpc.CallOption) (*ExplainResponse, error)
	// Persist and publish a JWT-SVID revocation. This is permission-gated by a
	// dedicated `revoke` admin op over `broker.revoke`; no data-plane grant
	// implies it. The broker requires a configured `revocation_store=jwt-svid`
	// backing key so the revocation survives restart.
	Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AdminService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AdminService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Readiness(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadinessResponse)
	err := c.cc.Invoke(ctx, AdminService_Readiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[0], AdminService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_WatchClient = grpc.ServerStreamingClient[Event]

func (c *adminServiceClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadResponse)
	err := c.cc.Invoke(ctx, AdminService_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Explain(ctx context.Context, in *ExplainRequest, opts ...grpc.CallOption) (*ExplainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainResponse)
	err := c.cc.Invoke(ctx, AdminService_Explain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeResponse)
	err := c.cc.Invoke(ctx, AdminService_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// Broker introspection and change notifications.
type AdminServiceServer interface {
	// Report backend, version, and protocol.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Liveness: is the broker process up and serving the socket? Cheap,
	// always-answerable, never touches a backend. A successful response means the
	// daemon is alive; it says nothing about whether it can serve data-plane ops.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Readiness: can the broker actually serve? Probes per-backend reachability
	// and every catalog key's material, and reports whether serving would fail
	// closed (an unreachable backend, or a `missing=error` key whose material is
	// absent). The detail is a non-secret SUMMARY (counts + a coarse reason): it
	// never returns key names, key material, or the catalog inventory.
	Readiness(context.Context, *ReadinessRequest) (*ReadinessResponse, error)
	// Stream change events (key rotations, bundle changes, revocations).
	Watch(*WatchRequest, grpc.ServerStreamingServer[Event]) error
	// Hot-reload the catalog/policy generation FROM DISK (basil-atq). The broker
	// re-reads the catalog/policy from the same on-disk paths it was started with,
	// runs the full startup/`check` validation, and, on success, atomically swaps
	// in a new generation. This RPC is permission-gated by a dedicated `reload`
	// policy op (NOT implied by any data-plane grant) and peer-cred attested; both
	// the success (generation change) and a denial are audited.
	//
	// TRUST BOUNDARY: the request carries NO catalog/policy bytes: the only input
	// is `check` (dry-run). Config is taken from disk (Nix/root-owned) only, so the
	// wire can never inject policy. A `check=true` request validates the candidate
	// and reports the would-be outcome WITHOUT swapping the serving generation.
	Reload(context.Context, *ReloadRequest) (*ReloadResponse, error)
	// Explain a policy decision against the currently serving generation. This is
	// permission-gated by a dedicated `explain` admin op over `broker.explain`
	// because it exposes policy reachability; no data-plane grant implies it.
	Explain(context.Context, *ExplainRequest) (*ExplainResponse, error)
	// Persist and publish a JWT-SVID revocation. This is permission-gated by a
	// dedicated `revoke` admin op over `broker.revoke`; no data-plane grant
	// implies it. The broker requires a configured `revocation_store=jwt-svid`
	// backing key so the revocation survives restart.
	Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedAdminServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAdminServiceServer) Readiness(context.Context, *ReadinessRequest) (*ReadinessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Readiness not implemented")
}
func (UnimplementedAdminServiceServer) Watch(*WatchRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedAdminServiceServer) Reload(context.Context, *ReloadRequest) (*ReloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedAdminServiceServer) Explain(context.Context, *ExplainRequest) (*ExplainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Explain not implemented")
}
func (UnimplementedAdminServiceServer) Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Readiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Readiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Readiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Readiness(ctx, req.(*ReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).Watch(m, &grpc.GenericServerStream[WatchRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AdminService_WatchServer = grpc.ServerStreamingServer[Event]

func _AdminService_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Explain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Explain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Explain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Explain(ctx, req.(*ExplainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Revoke(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basil.broker.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _AdminService_Status_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _AdminService_Health_Handler,
		},
		{
			MethodName: "Readiness",
			Handler:    _AdminService_Readiness_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _AdminService_Reload_Handler,
		},
		{
			MethodName: "Explain",
			Handler:    _AdminService_Explain_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _AdminService_Revoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _AdminService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "basil/broker/v1/broker.proto",
}
