// SPDX-FileCopyrightText: 2026 OpenBasil Contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: basil/broker/v1/nix_cache.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Result of a Nix cache key enrollment request.
type NixCacheEnrollmentDisposition int32

const (
	NixCacheEnrollmentDisposition_NIX_CACHE_ENROLLMENT_DISPOSITION_UNSPECIFIED NixCacheEnrollmentDisposition = 0
	NixCacheEnrollmentDisposition_NIX_CACHE_ENROLLMENT_DISPOSITION_CREATED     NixCacheEnrollmentDisposition = 1
	NixCacheEnrollmentDisposition_NIX_CACHE_ENROLLMENT_DISPOSITION_EXISTING    NixCacheEnrollmentDisposition = 2
)

// Enum value maps for NixCacheEnrollmentDisposition.
var (
	NixCacheEnrollmentDisposition_name = map[int32]string{
		0: "NIX_CACHE_ENROLLMENT_DISPOSITION_UNSPECIFIED",
		1: "NIX_CACHE_ENROLLMENT_DISPOSITION_CREATED",
		2: "NIX_CACHE_ENROLLMENT_DISPOSITION_EXISTING",
	}
	NixCacheEnrollmentDisposition_value = map[string]int32{
		"NIX_CACHE_ENROLLMENT_DISPOSITION_UNSPECIFIED": 0,
		"NIX_CACHE_ENROLLMENT_DISPOSITION_CREATED":     1,
		"NIX_CACHE_ENROLLMENT_DISPOSITION_EXISTING":    2,
	}
)

func (x NixCacheEnrollmentDisposition) Enum() *NixCacheEnrollmentDisposition {
	p := new(NixCacheEnrollmentDisposition)
	*p = x
	return p
}

func (x NixCacheEnrollmentDisposition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NixCacheEnrollmentDisposition) Descriptor() protoreflect.EnumDescriptor {
	return file_basil_broker_v1_nix_cache_proto_enumTypes[0].Descriptor()
}

func (NixCacheEnrollmentDisposition) Type() protoreflect.EnumType {
	return &file_basil_broker_v1_nix_cache_proto_enumTypes[0]
}

func (x NixCacheEnrollmentDisposition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NixCacheEnrollmentDisposition.Descriptor instead.
func (NixCacheEnrollmentDisposition) EnumDescriptor() ([]byte, []int) {
	return file_basil_broker_v1_nix_cache_proto_rawDescGZIP(), []int{0}
}

// Request the enrolled identity for one Nix binary-cache key.
type DescribeNixCacheKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	BatchId       []byte                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	RequestId     []byte                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeNixCacheKeyRequest) Reset() {
	*x = DescribeNixCacheKeyRequest{}
	mi := &file_basil_broker_v1_nix_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeNixCacheKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeNixCacheKeyRequest) ProtoMessage() {}

func (x *DescribeNixCacheKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basil_broker_v1_nix_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeNixCacheKeyRequest.ProtoReflect.Descriptor instead.
func (*DescribeNixCacheKeyRequest) Descriptor() ([]byte, []int) {
	return file_basil_broker_v1_nix_cache_proto_rawDescGZIP(), []int{0}
}

func (x *DescribeNixCacheKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *DescribeNixCacheKeyRequest) GetBatchId() []byte {
	if x != nil {
		return x.BatchId
	}
	return nil
}

func (x *DescribeNixCacheKeyRequest) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

// Enrolled Nix verifier identity.
type DescribeNixCacheKeyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KeyName        string                 `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	PublicKey      []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	BackendVersion uint32                 `protobuf:"varint,3,opt,name=backend_version,json=backendVersion,proto3" json:"backend_version,omitempty"`
	BatchId        []byte                 `protobuf:"bytes,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	RequestId      []byte                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DescribeNixCacheKeyResponse) Reset() {
	*x = DescribeNixCacheKeyResponse{}
	mi := &file_basil_broker_v1_nix_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeNixCacheKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeNixCacheKeyResponse) ProtoMessage() {}

func (x *DescribeNixCacheKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basil_broker_v1_nix_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeNixCacheKeyResponse.ProtoReflect.Descriptor instead.
func (*DescribeNixCacheKeyResponse) Descriptor() ([]byte, []int) {
	return file_basil_broker_v1_nix_cache_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeNixCacheKeyResponse) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *DescribeNixCacheKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *DescribeNixCacheKeyResponse) GetBackendVersion() uint32 {
	if x != nil {
		return x.BackendVersion
	}
	return 0
}

func (x *DescribeNixCacheKeyResponse) GetBatchId() []byte {
	if x != nil {
		return x.BatchId
	}
	return nil
}

func (x *DescribeNixCacheKeyResponse) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

// Request creation or compare-only validation of a pending Nix cache key.
type EnrollNixCacheKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	BatchId       []byte                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	RequestId     []byte                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollNixCacheKeyRequest) Reset() {
	*x = EnrollNixCacheKeyRequest{}
	mi := &file_basil_broker_v1_nix_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollNixCacheKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollNixCacheKeyRequest) ProtoMessage() {}

func (x *EnrollNixCacheKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basil_broker_v1_nix_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollNixCacheKeyRequest.ProtoReflect.Descriptor instead.
func (*EnrollNixCacheKeyRequest) Descriptor() ([]byte, []int) {
	return file_basil_broker_v1_nix_cache_proto_rawDescGZIP(), []int{2}
}

func (x *EnrollNixCacheKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *EnrollNixCacheKeyRequest) GetBatchId() []byte {
	if x != nil {
		return x.BatchId
	}
	return nil
}

func (x *EnrollNixCacheKeyRequest) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

// Public-only enrollment result.
type EnrollNixCacheKeyResponse struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	KeyName        string                        `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	PublicKey      []byte                        `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	BackendVersion uint32                        `protobuf:"varint,3,opt,name=backend_version,json=backendVersion,proto3" json:"backend_version,omitempty"`
	Disposition    NixCacheEnrollmentDisposition `protobuf:"varint,4,opt,name=disposition,proto3,enum=basil.broker.v1.NixCacheEnrollmentDisposition" json:"disposition,omitempty"`
	BatchId        []byte                        `protobuf:"bytes,5,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	RequestId      []byte                        `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnrollNixCacheKeyResponse) Reset() {
	*x = EnrollNixCacheKeyResponse{}
	mi := &file_basil_broker_v1_nix_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollNixCacheKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollNixCacheKeyResponse) ProtoMessage() {}

func (x *EnrollNixCacheKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basil_broker_v1_nix_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollNixCacheKeyResponse.ProtoReflect.Descriptor instead.
func (*EnrollNixCacheKeyResponse) Descriptor() ([]byte, []int) {
	return file_basil_broker_v1_nix_cache_proto_rawDescGZIP(), []int{3}
}

func (x *EnrollNixCacheKeyResponse) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *EnrollNixCacheKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *EnrollNixCacheKeyResponse) GetBackendVersion() uint32 {
	if x != nil {
		return x.BackendVersion
	}
	return 0
}

func (x *EnrollNixCacheKeyResponse) GetDisposition() NixCacheEnrollmentDisposition {
	if x != nil {
		return x.Disposition
	}
	return NixCacheEnrollmentDisposition_NIX_CACHE_ENROLLMENT_DISPOSITION_UNSPECIFIED
}

func (x *EnrollNixCacheKeyResponse) GetBatchId() []byte {
	if x != nil {
		return x.BatchId
	}
	return nil
}

func (x *EnrollNixCacheKeyResponse) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

// Request a signature over one canonical Nix path-info fingerprint.
type SignNixCacheFingerprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Profile       string                 `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Fingerprint   []byte                 `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	BatchId       []byte                 `protobuf:"bytes,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	RequestId     []byte                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignNixCacheFingerprintRequest) Reset() {
	*x = SignNixCacheFingerprintRequest{}
	mi := &file_basil_broker_v1_nix_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignNixCacheFingerprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignNixCacheFingerprintRequest) ProtoMessage() {}

func (x *SignNixCacheFingerprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basil_broker_v1_nix_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignNixCacheFingerprintRequest.ProtoReflect.Descriptor instead.
func (*SignNixCacheFingerprintRequest) Descriptor() ([]byte, []int) {
	return file_basil_broker_v1_nix_cache_proto_rawDescGZIP(), []int{4}
}

func (x *SignNixCacheFingerprintRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignNixCacheFingerprintRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *SignNixCacheFingerprintRequest) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *SignNixCacheFingerprintRequest) GetBatchId() []byte {
	if x != nil {
		return x.BatchId
	}
	return nil
}

func (x *SignNixCacheFingerprintRequest) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

// Signature and enrolled verifier identity for one Nix path-info fingerprint.
type SignNixCacheFingerprintResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KeyName        string                 `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	PublicKey      []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	BackendVersion uint32                 `protobuf:"varint,3,opt,name=backend_version,json=backendVersion,proto3" json:"backend_version,omitempty"`
	Signature      []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	BatchId        []byte                 `protobuf:"bytes,5,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	RequestId      []byte                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignNixCacheFingerprintResponse) Reset() {
	*x = SignNixCacheFingerprintResponse{}
	mi := &file_basil_broker_v1_nix_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignNixCacheFingerprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignNixCacheFingerprintResponse) ProtoMessage() {}

func (x *SignNixCacheFingerprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basil_broker_v1_nix_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignNixCacheFingerprintResponse.ProtoReflect.Descriptor instead.
func (*SignNixCacheFingerprintResponse) Descriptor() ([]byte, []int) {
	return file_basil_broker_v1_nix_cache_proto_rawDescGZIP(), []int{5}
}

func (x *SignNixCacheFingerprintResponse) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *SignNixCacheFingerprintResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SignNixCacheFingerprintResponse) GetBackendVersion() uint32 {
	if x != nil {
		return x.BackendVersion
	}
	return 0
}

func (x *SignNixCacheFingerprintResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignNixCacheFingerprintResponse) GetBatchId() []byte {
	if x != nil {
		return x.BatchId
	}
	return nil
}

func (x *SignNixCacheFingerprintResponse) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

var File_basil_broker_v1_nix_cache_proto protoreflect.FileDescriptor

const file_basil_broker_v1_nix_cache_proto_rawDesc = "" +
	"\n" +
	"\x1fbasil/broker/v1/nix_cache.proto\x12\x0fbasil.broker.v1\"m\n" +
	"\x1aDescribeNixCacheKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\fR\abatchId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\fR\trequestId\"\xba\x01\n" +
	"\x1bDescribeNixCacheKeyResponse\x12\x19\n" +
	"\bkey_name\x18\x01 \x01(\tR\akeyName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12'\n" +
	"\x0fbackend_version\x18\x03 \x01(\rR\x0ebackendVersion\x12\x19\n" +
	"\bbatch_id\x18\x04 \x01(\fR\abatchId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\fR\trequestId\"k\n" +
	"\x18EnrollNixCacheKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\fR\abatchId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\fR\trequestId\"\x8a\x02\n" +
	"\x19EnrollNixCacheKeyResponse\x12\x19\n" +
	"\bkey_name\x18\x01 \x01(\tR\akeyName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12'\n" +
	"\x0fbackend_version\x18\x03 \x01(\rR\x0ebackendVersion\x12P\n" +
	"\vdisposition\x18\x04 \x01(\x0e2..basil.broker.v1.NixCacheEnrollmentDispositionR\vdisposition\x12\x19\n" +
	"\bbatch_id\x18\x05 \x01(\fR\abatchId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\fR\trequestId\"\xad\x01\n" +
	"\x1eSignNixCacheFingerprintRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\fR\vfingerprint\x12\x19\n" +
	"\bbatch_id\x18\x04 \x01(\fR\abatchId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\fR\trequestId\"\xdc\x01\n" +
	"\x1fSignNixCacheFingerprintResponse\x12\x19\n" +
	"\bkey_name\x18\x01 \x01(\tR\akeyName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12'\n" +
	"\x0fbackend_version\x18\x03 \x01(\rR\x0ebackendVersion\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x19\n" +
	"\bbatch_id\x18\x05 \x01(\fR\abatchId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\fR\trequestId*\xae\x01\n" +
	"\x1dNixCacheEnrollmentDisposition\x120\n" +
	",NIX_CACHE_ENROLLMENT_DISPOSITION_UNSPECIFIED\x10\x00\x12,\n" +
	"(NIX_CACHE_ENROLLMENT_DISPOSITION_CREATED\x10\x01\x12-\n" +
	")NIX_CACHE_ENROLLMENT_DISPOSITION_EXISTING\x10\x022\xed\x02\n" +
	"\x0fNixCacheService\x12p\n" +
	"\x13DescribeNixCacheKey\x12+.basil.broker.v1.DescribeNixCacheKeyRequest\x1a,.basil.broker.v1.DescribeNixCacheKeyResponse\x12j\n" +
	"\x11EnrollNixCacheKey\x12).basil.broker.v1.EnrollNixCacheKeyRequest\x1a*.basil.broker.v1.EnrollNixCacheKeyResponse\x12|\n" +
	"\x17SignNixCacheFingerprint\x12/.basil.broker.v1.SignNixCacheFingerprintRequest\x1a0.basil.broker.v1.SignNixCacheFingerprintResponseb\x06proto3"

var (
	file_basil_broker_v1_nix_cache_proto_rawDescOnce sync.Once
	file_basil_broker_v1_nix_cache_proto_rawDescData []byte
)

func file_basil_broker_v1_nix_cache_proto_rawDescGZIP() []byte {
	file_basil_broker_v1_nix_cache_proto_rawDescOnce.Do(func() {
		file_basil_broker_v1_nix_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basil_broker_v1_nix_cache_proto_rawDesc), len(file_basil_broker_v1_nix_cache_proto_rawDesc)))
	})
	return file_basil_broker_v1_nix_cache_proto_rawDescData
}

var file_basil_broker_v1_nix_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_basil_broker_v1_nix_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_basil_broker_v1_nix_cache_proto_goTypes = []any{
	(NixCacheEnrollmentDisposition)(0),      // 0: basil.broker.v1.NixCacheEnrollmentDisposition
	(*DescribeNixCacheKeyRequest)(nil),      // 1: basil.broker.v1.DescribeNixCacheKeyRequest
	(*DescribeNixCacheKeyResponse)(nil),     // 2: basil.broker.v1.DescribeNixCacheKeyResponse
	(*EnrollNixCacheKeyRequest)(nil),        // 3: basil.broker.v1.EnrollNixCacheKeyRequest
	(*EnrollNixCacheKeyResponse)(nil),       // 4: basil.broker.v1.EnrollNixCacheKeyResponse
	(*SignNixCacheFingerprintRequest)(nil),  // 5: basil.broker.v1.SignNixCacheFingerprintRequest
	(*SignNixCacheFingerprintResponse)(nil), // 6: basil.broker.v1.SignNixCacheFingerprintResponse
}
var file_basil_broker_v1_nix_cache_proto_depIdxs = []int32{
	0, // 0: basil.broker.v1.EnrollNixCacheKeyResponse.disposition:type_name -> basil.broker.v1.NixCacheEnrollmentDisposition
	1, // 1: basil.broker.v1.NixCacheService.DescribeNixCacheKey:input_type -> basil.broker.v1.DescribeNixCacheKeyRequest
	3, // 2: basil.broker.v1.NixCacheService.EnrollNixCacheKey:input_type -> basil.broker.v1.EnrollNixCacheKeyRequest
	5, // 3: basil.broker.v1.NixCacheService.SignNixCacheFingerprint:input_type -> basil.broker.v1.SignNixCacheFingerprintRequest
	2, // 4: basil.broker.v1.NixCacheService.DescribeNixCacheKey:output_type -> basil.broker.v1.DescribeNixCacheKeyResponse
	4, // 5: basil.broker.v1.NixCacheService.EnrollNixCacheKey:output_type -> basil.broker.v1.EnrollNixCacheKeyResponse
	6, // 6: basil.broker.v1.NixCacheService.SignNixCacheFingerprint:output_type -> basil.broker.v1.SignNixCacheFingerprintResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_basil_broker_v1_nix_cache_proto_init() }
func file_basil_broker_v1_nix_cache_proto_init() {
	if File_basil_broker_v1_nix_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basil_broker_v1_nix_cache_proto_rawDesc), len(file_basil_broker_v1_nix_cache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_basil_broker_v1_nix_cache_proto_goTypes,
		DependencyIndexes: file_basil_broker_v1_nix_cache_proto_depIdxs,
		EnumInfos:         file_basil_broker_v1_nix_cache_proto_enumTypes,
		MessageInfos:      file_basil_broker_v1_nix_cache_proto_msgTypes,
	}.Build()
	File_basil_broker_v1_nix_cache_proto = out.File
	file_basil_broker_v1_nix_cache_proto_goTypes = nil
	file_basil_broker_v1_nix_cache_proto_depIdxs = nil
}
