// SPDX-FileCopyrightText: 2026 OpenBasil Contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: basil/broker/v1/nix_cache.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NixCacheService_DescribeNixCacheKey_FullMethodName     = "/basil.broker.v1.NixCacheService/DescribeNixCacheKey"
	NixCacheService_EnrollNixCacheKey_FullMethodName       = "/basil.broker.v1.NixCacheService/EnrollNixCacheKey"
	NixCacheService_SignNixCacheFingerprint_FullMethodName = "/basil.broker.v1.NixCacheService/SignNixCacheFingerprint"
)

// NixCacheServiceClient is the client API for NixCacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Purpose-specific Nix binary-cache key custody operations.
type NixCacheServiceClient interface {
	// Return the enrolled Nix verifier identity for a catalog key.
	DescribeNixCacheKey(ctx context.Context, in *DescribeNixCacheKeyRequest, opts ...grpc.CallOption) (*DescribeNixCacheKeyResponse, error)
	// Ensure and enroll a pending Nix binary-cache key.
	EnrollNixCacheKey(ctx context.Context, in *EnrollNixCacheKeyRequest, opts ...grpc.CallOption) (*EnrollNixCacheKeyResponse, error)
	// Sign one canonical PATH_INFO_V1 fingerprint.
	SignNixCacheFingerprint(ctx context.Context, in *SignNixCacheFingerprintRequest, opts ...grpc.CallOption) (*SignNixCacheFingerprintResponse, error)
}

type nixCacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNixCacheServiceClient(cc grpc.ClientConnInterface) NixCacheServiceClient {
	return &nixCacheServiceClient{cc}
}

func (c *nixCacheServiceClient) DescribeNixCacheKey(ctx context.Context, in *DescribeNixCacheKeyRequest, opts ...grpc.CallOption) (*DescribeNixCacheKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeNixCacheKeyResponse)
	err := c.cc.Invoke(ctx, NixCacheService_DescribeNixCacheKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nixCacheServiceClient) EnrollNixCacheKey(ctx context.Context, in *EnrollNixCacheKeyRequest, opts ...grpc.CallOption) (*EnrollNixCacheKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollNixCacheKeyResponse)
	err := c.cc.Invoke(ctx, NixCacheService_EnrollNixCacheKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nixCacheServiceClient) SignNixCacheFingerprint(ctx context.Context, in *SignNixCacheFingerprintRequest, opts ...grpc.CallOption) (*SignNixCacheFingerprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignNixCacheFingerprintResponse)
	err := c.cc.Invoke(ctx, NixCacheService_SignNixCacheFingerprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NixCacheServiceServer is the server API for NixCacheService service.
// All implementations must embed UnimplementedNixCacheServiceServer
// for forward compatibility.
//
// Purpose-specific Nix binary-cache key custody operations.
type NixCacheServiceServer interface {
	// Return the enrolled Nix verifier identity for a catalog key.
	DescribeNixCacheKey(context.Context, *DescribeNixCacheKeyRequest) (*DescribeNixCacheKeyResponse, error)
	// Ensure and enroll a pending Nix binary-cache key.
	EnrollNixCacheKey(context.Context, *EnrollNixCacheKeyRequest) (*EnrollNixCacheKeyResponse, error)
	// Sign one canonical PATH_INFO_V1 fingerprint.
	SignNixCacheFingerprint(context.Context, *SignNixCacheFingerprintRequest) (*SignNixCacheFingerprintResponse, error)
	mustEmbedUnimplementedNixCacheServiceServer()
}

// UnimplementedNixCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNixCacheServiceServer struct{}

func (UnimplementedNixCacheServiceServer) DescribeNixCacheKey(context.Context, *DescribeNixCacheKeyRequest) (*DescribeNixCacheKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeNixCacheKey not implemented")
}
func (UnimplementedNixCacheServiceServer) EnrollNixCacheKey(context.Context, *EnrollNixCacheKeyRequest) (*EnrollNixCacheKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollNixCacheKey not implemented")
}
func (UnimplementedNixCacheServiceServer) SignNixCacheFingerprint(context.Context, *SignNixCacheFingerprintRequest) (*SignNixCacheFingerprintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignNixCacheFingerprint not implemented")
}
func (UnimplementedNixCacheServiceServer) mustEmbedUnimplementedNixCacheServiceServer() {}
func (UnimplementedNixCacheServiceServer) testEmbeddedByValue()                         {}

// UnsafeNixCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NixCacheServiceServer will
// result in compilation errors.
type UnsafeNixCacheServiceServer interface {
	mustEmbedUnimplementedNixCacheServiceServer()
}

func RegisterNixCacheServiceServer(s grpc.ServiceRegistrar, srv NixCacheServiceServer) {
	// If the following call panics, it indicates UnimplementedNixCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NixCacheService_ServiceDesc, srv)
}

func _NixCacheService_DescribeNixCacheKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeNixCacheKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NixCacheServiceServer).DescribeNixCacheKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NixCacheService_DescribeNixCacheKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NixCacheServiceServer).DescribeNixCacheKey(ctx, req.(*DescribeNixCacheKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NixCacheService_EnrollNixCacheKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollNixCacheKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NixCacheServiceServer).EnrollNixCacheKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NixCacheService_EnrollNixCacheKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NixCacheServiceServer).EnrollNixCacheKey(ctx, req.(*EnrollNixCacheKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NixCacheService_SignNixCacheFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignNixCacheFingerprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NixCacheServiceServer).SignNixCacheFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NixCacheService_SignNixCacheFingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NixCacheServiceServer).SignNixCacheFingerprint(ctx, req.(*SignNixCacheFingerprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NixCacheService_ServiceDesc is the grpc.ServiceDesc for NixCacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NixCacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basil.broker.v1.NixCacheService",
	HandlerType: (*NixCacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeNixCacheKey",
			Handler:    _NixCacheService_DescribeNixCacheKey_Handler,
		},
		{
			MethodName: "EnrollNixCacheKey",
			Handler:    _NixCacheService_EnrollNixCacheKey_Handler,
		},
		{
			MethodName: "SignNixCacheFingerprint",
			Handler:    _NixCacheService_SignNixCacheFingerprint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "basil/broker/v1/nix_cache.proto",
}
